//campaign types const
export const CHANGE_TAB = 'CHANGE_TAB';
export const FILTER_NAME_CHANGE = 'FILTER_NAME_CHANGE';
export const FILTER_CLICKSTATE_CHANGE = 'FILTER_CLICKSTATE_CHANGE';
export const CAMPAIGN_COUNTPERPAGE_CHANGE = 'CAMPAIGN_COUNTPERPAGE_CHANGE';
