//proxy base url
export const PROXY_URL = 'http://localhost:5000/api'

//campaign types const
export const CHANGE_TAB = 'CHANGE_TAB';
export const FILTER_NAME_CHANGE = 'FILTER_NAME_CHANGE';
export const FILTER_CLICKSTATE_CHANGE = 'FILTER_CLICKSTATE_CHANGE';
export const CAMPAIGN_COUNTPERPAGE_CHANGE = 'CAMPAIGN_COUNTPERPAGE_CHANGE';
export const CREATE_NEW_CAMPAIGN = 'CREATE_NEW_CAMPAIGN';
export const CHANGE_NEW_CAMPAIGN_ATTR = 'CHANGE_NEW_CAMPAIGN_ATTR';
export const ChANGE_NEW_SELECTABLE = 'ChANGE_NEW_SELECTABLE';
export const REVERSE_PRESET_SELECTABLE = 'REVERSE_PRESET_SELECTABLE';
export const ADD_NEW_PRESET = 'ADD_NEW_PRESET';
export const CHANGE_NEW_CAMPAIGN_TITLE = 'CHANGE_NEW_CAMPAIGN_TITLE';
export const GET_PRESETS = 'GET_PRESETS';
export const ADD_NEW_CAMPAIGN_FROM_PRESET = 'ADD_NEW_CAMPAIGN_FROM_PRESET';
export const GET_CAPAIGN_FROM_TIKTOK = 'GET_CAPAIGN_FROM_TIKTOK';
export const GETED_CAPAIGN_FROM_TIKTOK = 'GETED_CAPAIGN_FROM_TIKTOK';
export const ADD_CAMPAIGN_TO_TIKTOK = 'ADD_CAMPAIGN_TO_TIKTOK';
export const ADD_FILTER_NAME = 'ADD_FILTER_NAME';
export const REMOVE_FILTER_NAME = 'REMOVE_FILTER_NAME';

//upload csv
export const GET_CAMPAIGN_FROM_CSV = 'GET_CAMPAIGN_FROM_CSV';
export const GETED_CAMPAIGN_FROM_CSV = 'GETED_CAMPAIGN_FROM_CSV';

export const ADD_FILTER_CAMPAIGN_NAME = 'ADD_FILTER_CAMPAIGN_NAME'
export const ADD_FILTER_GROUP_NAME = 'ADD_FILTER_GROUP_NAME'
export const REMOVE_FILTER_CAMPAIGN_NAME = 'REMOVE_FILTER_CAMPAIGN_NAME'
export const REMOVE_FILTER_GROUP_NAME = 'REMOVE_FILTER_GROUP_NAME'
