//campaign types const
export const CHANGE_TAB = 'CHANGE_TAB';
export const FILTER_NAME_CHANGE = 'FILTER_NAME_CHANGE';
export const FILTER_CLICKSTATE_CHANGE = 'FILTER_CLICKSTATE_CHANGE';
export const CAMPAIGN_COUNTPERPAGE_CHANGE = 'CAMPAIGN_COUNTPERPAGE_CHANGE';

export const CREATE_NEW_CAMPAIGN = 'CREATE_NEW_CAMPAIGN';
export const CHANGE_NEW_CAMPAIGN_ATTR = 'CHANGE_NEW_CAMPAIGN_ATTR';
export const ChANGE_NEW_SELECTABLE = 'ChANGE_NEW_SELECTABLE';
export const REVERSE_PRESET_SELECTABLE = 'REVERSE_PRESET_SELECTABLE';
export const ADD_NEW_PRESET = 'ADD_NEW_PRESET';
export const CHANGE_NEW_CAMPAIGN_TITLE = 'CHANGE_NEW_CAMPAIGN_TITLE';
export const GET_PRESETS = 'GET_PRESETS';
export const ADD_NEW_CAMPAIGN_FROM_PRESET = 'ADD_NEW_CAMPAIGN_FROM_PRESET';